  update users set country = 'Afghanistan' where country = 'AF';
  update users set country = 'Albania' where country = 'AL';
  update users set country = 'Algeria' where country = 'DZ';
  update users set country = 'American Samoa' where country = 'AS';
  update users set country = 'Andorra' where country = 'AD';
  update users set country = 'Angola' where country = 'AO';
  update users set country = 'Anguilla' where country = 'AI';
  update users set country = 'Antarctica' where country = 'AQ';
  update users set country = 'Antigua and Barbuda' where country = 'AG';
  update users set country = 'Argentina' where country = 'AR';
  update users set country = 'Armenia' where country = 'AM';
  update users set country = 'Aruba' where country = 'AW';
  update users set country = 'Australia' where country = 'AU';
  update users set country = 'Austria' where country = 'AT';
  update users set country = 'Azerbaijan' where country = 'AZ';
  update users set country = 'Bahamas' where country = 'BS';
  update users set country = 'Bahrain' where country = 'BH';
  update users set country = 'Bangladesh' where country = 'BD';
  update users set country = 'Barbados' where country = 'BB';
  update users set country = 'Belarus' where country = 'BY';
  update users set country = 'Belgium' where country = 'BE';
  update users set country = 'Belize' where country = 'BZ';
  update users set country = 'Benin' where country = 'BJ';
  update users set country = 'Bermuda' where country = 'BM';
  update users set country = 'Bhutan' where country = 'BT';
  update users set country = 'Bolivia' where country = 'BO';
  update users set country = 'Bosnia and Herzegovina' where country = 'BA';
  update users set country = 'Botswana' where country = 'BW';
  update users set country = 'Brazil' where country = 'BR';
  update users set country = 'British Indian Ocean Territory' where country = 'IO';
  update users set country = 'British Virgin Islands' where country = 'VG';
  update users set country = 'Brunei' where country = 'BN';
  update users set country = 'Bulgaria' where country = 'BG';
  update users set country = 'Burkina Faso' where country = 'BF';
  update users set country = 'Burundi' where country = 'BI';
  update users set country = 'Cambodia' where country = 'KH';
  update users set country = 'Cameroon' where country = 'CM';
  update users set country = 'Canada' where country = 'CA';
  update users set country = 'Cape Verde' where country = 'CV';
  update users set country = 'Cayman Islands' where country = 'KY';
  update users set country = 'Central African Republic' where country = 'CF';
  update users set country = 'Chad' where country = 'TD';
  update users set country = 'Chile' where country = 'CL';
  update users set country = 'China' where country = 'CN';
  update users set country = 'Christmas Island' where country = 'CX';
  update users set country = 'Cocos Islands' where country = 'CC';
  update users set country = 'Colombia' where country = 'CO';
  update users set country = 'Comoros' where country = 'KM';
  update users set country = 'Cook Islands' where country = 'CK';
  update users set country = 'Costa Rica' where country = 'CR';
  update users set country = 'Croatia' where country = 'HR';
  update users set country = 'Cuba' where country = 'CU';
  update users set country = 'Curacao' where country = 'CW';
  update users set country = 'Cyprus' where country = 'CY';
  update users set country = 'Czech Republic' where country = 'CZ';
  update users set country = 'Democratic Republic of the Congo' where country = 'CD';
  update users set country = 'Denmark' where country = 'DK';
  update users set country = 'Djibouti' where country = 'DJ';
  update users set country = 'Dominica' where country = 'DM';
  update users set country = 'Dominican Republic' where country = 'DO';
  update users set country = 'East Timor' where country = 'TL';
  update users set country = 'Ecuador' where country = 'EC';
  update users set country = 'Egypt' where country = 'EG';
  update users set country = 'El Salvador' where country = 'SV';
  update users set country = 'Equatorial Guinea' where country = 'GQ';
  update users set country = 'Eritrea' where country = 'ER';
  update users set country = 'Estonia' where country = 'EE';
  update users set country = 'Ethiopia' where country = 'ET';
  update users set country = 'Falkland Islands' where country = 'FK';
  update users set country = 'Faroe Islands' where country = 'FO';
  update users set country = 'Fiji' where country = 'FJ';
  update users set country = 'Finland' where country = 'FI';
  update users set country = 'France' where country = 'FR';
  update users set country = 'French Polynesia' where country = 'PF';
  update users set country = 'Gabon' where country = 'GA';
  update users set country = 'Gambia' where country = 'GM';
  update users set country = 'Georgia' where country = 'GE';
  update users set country = 'Germany' where country = 'DE';
  update users set country = 'Ghana' where country = 'GH';
  update users set country = 'Gibraltar' where country = 'GI';
  update users set country = 'Greece' where country = 'GR';
  update users set country = 'Greenland' where country = 'GL';
  update users set country = 'Grenada' where country = 'GD';
  update users set country = 'Guam' where country = 'GU';
  update users set country = 'Guatemala' where country = 'GT';
  update users set country = 'Guernsey' where country = 'GG';
  update users set country = 'Guinea' where country = 'GN';
  update users set country = 'Guinea-Bissau' where country = 'GW';
  update users set country = 'Guyana' where country = 'GY';
  update users set country = 'Haiti' where country = 'HT';
  update users set country = 'Honduras' where country = 'HN';
  update users set country = 'Hong Kong' where country = 'HK';
  update users set country = 'Hungary' where country = 'HU';
  update users set country = 'Iceland' where country = 'IS';
  update users set country = 'India' where country = 'IN';
  update users set country = 'Indonesia' where country = 'ID';
  update users set country = 'Iran' where country = 'IR';
  update users set country = 'Iraq' where country = 'IQ';
  update users set country = 'Ireland' where country = 'IE';
  update users set country = 'Isle of Man' where country = 'IM';
  update users set country = 'Israel' where country = 'IL';
  update users set country = 'Italy' where country = 'IT';
  update users set country = 'Ivory Coast' where country = 'CI';
  update users set country = 'Jamaica' where country = 'JM';
  update users set country = 'Japan' where country = 'JP';
  update users set country = 'Jersey' where country = 'JE';
  update users set country = 'Jordan' where country = 'JO';
  update users set country = 'Kazakhstan' where country = 'KZ';
  update users set country = 'Kenya' where country = 'KE';
  update users set country = 'Kiribati' where country = 'KI';
  update users set country = 'Kosovo' where country = 'XK';
  update users set country = 'Kuwait' where country = 'KW';
  update users set country = 'Kyrgyzstan' where country = 'KG';
  update users set country = 'Laos' where country = 'LA';
  update users set country = 'Latvia' where country = 'LV';
  update users set country = 'Lebanon' where country = 'LB';
  update users set country = 'Lesotho' where country = 'LS';
  update users set country = 'Liberia' where country = 'LR';
  update users set country = 'Libya' where country = 'LY';
  update users set country = 'Liechtenstein' where country = 'LI';
  update users set country = 'Lithuania' where country = 'LT';
  update users set country = 'Luxembourg' where country = 'LU';
  update users set country = 'Macau' where country = 'MO';
  update users set country = 'Macedonia' where country = 'MK';
  update users set country = 'Madagascar' where country = 'MG';
  update users set country = 'Malawi' where country = 'MW';
  update users set country = 'Malaysia' where country = 'MY';
  update users set country = 'Maldives' where country = 'MV';
  update users set country = 'Mali' where country = 'ML';
  update users set country = 'Malta' where country = 'MT';
  update users set country = 'Marshall Islands' where country = 'MH';
  update users set country = 'Mauritania' where country = 'MR';
  update users set country = 'Mauritius' where country = 'MU';
  update users set country = 'Mayotte' where country = 'YT';
  update users set country = 'Mexico' where country = 'MX';
  update users set country = 'Micronesia' where country = 'FM';
  update users set country = 'Moldova' where country = 'MD';
  update users set country = 'Monaco' where country = 'MC';
  update users set country = 'Mongolia' where country = 'MN';
  update users set country = 'Montenegro' where country = 'ME';
  update users set country = 'Montserrat' where country = 'MS';
  update users set country = 'Morocco' where country = 'MA';
  update users set country = 'Mozambique' where country = 'MZ';
  update users set country = 'Myanmar' where country = 'MM';
  update users set country = 'Namibia' where country = 'NA';
  update users set country = 'Nauru' where country = 'NR';
  update users set country = 'Nepal' where country = 'NP';
  update users set country = 'Netherlands' where country = 'NL';
  update users set country = 'Netherlands Antilles' where country = 'AN';
  update users set country = 'New Caledonia' where country = 'NC';
  update users set country = 'New Zealand' where country = 'NZ';
  update users set country = 'Nicaragua' where country = 'NI';
  update users set country = 'Niger' where country = 'NE';
  update users set country = 'Nigeria' where country = 'NG';
  update users set country = 'Niue' where country = 'NU';
  update users set country = 'North Korea' where country = 'KP';
  update users set country = 'Northern Mariana Islands' where country = 'MP';
  update users set country = 'Norway' where country = 'NO';
  update users set country = 'Oman' where country = 'OM';
  update users set country = 'Pakistan' where country = 'PK';
  update users set country = 'Palau' where country = 'PW';
  update users set country = 'Palestine' where country = 'PS';
  update users set country = 'Panama' where country = 'PA';
  update users set country = 'Papua New Guinea' where country = 'PG';
  update users set country = 'Paraguay' where country = 'PY';
  update users set country = 'Peru' where country = 'PE';
  update users set country = 'Philippines' where country = 'PH';
  update users set country = 'Pitcairn' where country = 'PN';
  update users set country = 'Poland' where country = 'PL';
  update users set country = 'Portugal' where country = 'PT';
  update users set country = 'Puerto Rico' where country = 'PR';
  update users set country = 'Qatar' where country = 'QA';
  update users set country = 'Republic of the Congo' where country = 'CG';
  update users set country = 'Reunion' where country = 'RE';
  update users set country = 'Romania' where country = 'RO';
  update users set country = 'Russia' where country = 'RU';
  update users set country = 'Rwanda' where country = 'RW';
  update users set country = 'Saint Barthelemy' where country = 'BL';
  update users set country = 'Saint Helena' where country = 'SH';
  update users set country = 'Saint Kitts and Nevis' where country = 'KN';
  update users set country = 'Saint Lucia' where country = 'LC';
  update users set country = 'Saint Martin' where country = 'MF';
  update users set country = 'Saint Pierre and Miquelon' where country = 'PM';
  update users set country = 'Saint Vincent and the Grenadines' where country = 'VC';
  update users set country = 'Samoa' where country = 'WS';
  update users set country = 'San Marino' where country = 'SM';
  update users set country = 'Sao Tome and Principe' where country = 'ST';
  update users set country = 'Saudi Arabia' where country = 'SA';
  update users set country = 'Senegal' where country = 'SN';
  update users set country = 'Serbia' where country = 'RS';
  update users set country = 'Seychelles' where country = 'SC';
  update users set country = 'Sierra Leone' where country = 'SL';
  update users set country = 'Singapore' where country = 'SG';
  update users set country = 'Sint Maarten' where country = 'SX';
  update users set country = 'Slovakia' where country = 'SK';
  update users set country = 'Slovenia' where country = 'SI';
  update users set country = 'Solomon Islands' where country = 'SB';
  update users set country = 'Somalia' where country = 'SO';
  update users set country = 'South Africa' where country = 'ZA';
  update users set country = 'South Korea' where country = 'KR';
  update users set country = 'South Sudan' where country = 'SS';
  update users set country = 'Spain' where country = 'ES';
  update users set country = 'Sri Lanka' where country = 'LK';
  update users set country = 'Sudan' where country = 'SD';
  update users set country = 'Suriname' where country = 'SR';
  update users set country = 'Svalbard and Jan Mayen' where country = 'SJ';
  update users set country = 'Swaziland' where country = 'SZ';
  update users set country = 'Sweden' where country = 'SE';
  update users set country = 'Switzerland' where country = 'CH';
  update users set country = 'Syria' where country = 'SY';
  update users set country = 'Taiwan' where country = 'TW';
  update users set country = 'Tajikistan' where country = 'TJ';
  update users set country = 'Tanzania' where country = 'TZ';
  update users set country = 'Thailand' where country = 'TH';
  update users set country = 'Togo' where country = 'TG';
  update users set country = 'Tokelau' where country = 'TK';
  update users set country = 'Tonga' where country = 'TO';
  update users set country = 'Trinidad and Tobago' where country = 'TT';
  update users set country = 'Tunisia' where country = 'TN';
  update users set country = 'Turkey' where country = 'TR';
  update users set country = 'Turkmenistan' where country = 'TM';
  update users set country = 'Turks and Caicos Islands' where country = 'TC';
  update users set country = 'Tuvalu' where country = 'TV';
  update users set country = 'U.S. Virgin Islands' where country = 'VI';
  update users set country = 'Uganda' where country = 'UG';
  update users set country = 'Ukraine' where country = 'UA';
  update users set country = 'United Arab Emirates' where country = 'AE';
  update users set country = 'United Kingdom' where country = 'GB';
  update users set country = 'United States' where country = 'US';
  update users set country = 'Uruguay' where country = 'UY';
  update users set country = 'Uzbekistan' where country = 'UZ';
  update users set country = 'Vanuatu' where country = 'VU';
  update users set country = 'Vatican' where country = 'VA';
  update users set country = 'Venezuela' where country = 'VE';
  update users set country = 'Vietnam' where country = 'VN';
  update users set country = 'Wallis and Futuna' where country = 'WF';
  update users set country = 'Western Sahara' where country = 'EH';
  update users set country = 'Yemen' where country = 'YE';
  update users set country = 'Zambia' where country = 'ZM';
  update users set country = 'Zimbabwe' where country = 'ZW';
